import { Router } from "express";
import { queueController } from "../controllers/queue.controller.js";
import { authenticate, authorize } from "../middleware/auth.js";
const router = Router();
router.get("/doctors", queueController.doctors);
router.post("/", authenticate, authorize("PASIEN"), queueController.create);
router.get("/mine", authenticate, authorize("PASIEN"), queueController.mine);
router.get("/staff", authenticate, authorize("PETUGAS", "SUPERADMIN"), queueController.staff);
router.patch("/:id/status", authenticate, authorize("PETUGAS", "SUPERADMIN"), queueController.status);
export const queueRoutes = router;
